// Binding declarations are generated by wrangler types. Secret values are never generated.
interface Env {
  OPENROUTER_API_KEY?: string;
  TURNSTILE_SECRET_KEY?: string;
  ABUSE_HASH_SECRET?: string;
}
